### ISSUE TITLE
5 vulnerabilities

### ISSUE THREAD

**Issue by Tonsheikh** [ton-blockchain/locker-contract#6]
1. The contract does not check if the user has sent at least 50 TON while depositing funds, which can lead to the contract accepting deposits below the minimum limit.

2. The contract does not have any mechanism to prevent the same user from depositing multiple times, which can result in that user receiving a disproportionate amount of rewards.

3. There is no mechanism to prevent the reward pool from being emptied before all the locked funds are released, which can result in some users not receiving their full rewards.

4. The contract does not have any mechanism to prevent the user from withdrawing more funds than they have released, which can result in a negative balance.

5. The contract does not have any mechanism to prevent the user from withdrawing funds before they have been fully released, which can result in a loss of funds for the user.

*********
Vulnerability solutions:

1. To solve this vulnerability, the contract should include a check to ensure that the user has sent at least 50 TON before accepting any deposits. This can be done by adding a conditional statement in the deposit function that checks the amount of TON sent by the user.

2. To prevent the same user from depositing multiple times, the contract can include a mapping that keeps track of the users who have already deposited funds. This mapping can be checked before accepting any deposits, and if the user has already deposited, their deposit can be rejected.

3. To prevent the reward pool from being emptied before all the locked funds are released, the contract can include a check that ensures that there are sufficient funds in the reward pool before releasing any rewards. This can be done by adding a conditional statement in the release function that checks the balance of the reward pool.

4. To prevent the user from withdrawing more funds than they have released, the contract can include a mapping that keeps track of the amount of funds released by each user. This mapping can be checked before allowing any withdrawals, and if the user has not released enough funds, their withdrawal can be rejected.

5. To prevent the user from withdrawing funds before they have been fully released, the contract can include a mapping that keeps track of the amount of funds released by each user, as well as the time at which they were released. This mapping can be checked before allowing any withdrawals, and if the funds have not been fully released or enough time has not passed, their withdrawal can be rejected.

**Comment by EmelyanenkoK** [comment]
AI generated nonsense.

Regarding 2 - it is expected that one user may deposit multiple times; in this case deposits should be summed up
